# Generated by Django 4.2 on 2023-04-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='party',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
